name: deploy

on: 
  pull_request_review:
    types: [submitted]

jobs:
  deploy:
    if: ${{ github.event.pull_request.base.ref == 'main' && github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: '0'
      - name: merge
        continue-on-error: true
        run: |
          git merge --ff-only ${{ github.event.pull_request.head.sha }}
          git push
